services:
  api-gateway:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: api-gateway
    restart: always
    ports:
      - "3000:3000"
    env_file:
      - .env.production
    volumes:
      - ./logs:/app/logs
      - /app/node_modules
    networks:
      - gateway-network
    
  # Mock services for testing
  user-service:
    build:
      context: ./mock/user-service
      dockerfile: Dockerfile
    container_name: user-service
    ports:
      - "3001:3000"
    environment:
      - PORT=3001
    networks:
      - gateway-network

  product-service:
    build:
      context: ./mock/products-service
      dockerfile: Dockerfile
    container_name: product-service
    ports:
      - "3002:3000"
    environment:
      - PORT=3002
    networks:
      - gateway-network

  order-service:
    build:
      context: ./mock/orders-service
      dockerfile: Dockerfile
    container_name: order-service
    ports:
      - "3003:3000"
    environment:
      - PORT=3003
    networks:
      - gateway-network

networks:
  gateway-network:
    driver: bridge
